services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: resume-backend
    ports:
      - "3001:3001"
    environment:
      FLASK_ENV: production
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    networks:
      - resume-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: resume-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE: http://backend:3001
    depends_on:
      - backend
    networks:
      - resume-network

networks:
  resume-network:
    driver: bridge