services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: resume-backend
    ports:
      - "3001:3001"
    environment:
      FLASK_ENV: production
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    networks:
      - resume-net

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        NEXT_PUBLIC_API_BASE: "http://backend:3001"
    container_name: resume-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - resume-net

networks:
  resume-net:
    driver: bridge